Fix CI

diff --git a/.github/workflows/imdbgraph-api.yml b/.github/workflows/imdbgraph-api.yml
--- a/.github/workflows/imdbgraph-api.yml
+++ b/.github/workflows/imdbgraph-api.yml
@@ -31,15 +31,37 @@ jobs:
           java-version: 22
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
-      - name: Build
-        run: ./gradlew bootJar -Pversion=${{ env.VERSION }}
       - name: Test
         run: ./gradlew check
-      - name: Upload JAR file
-        uses: actions/upload-artifact@v4
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
         with:
-          name: imdbgraph-api-${{ env.VERSION }}.jar
-          path: build/libs/imdbgraph-api-${{ env.VERSION }}.jar
+          report_paths: '**/build/test-results/test/TEST-*.xml'
       # https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
       - name: Publish Image
-        run: ./gradlew bootBuildImage --publishImage --imageName ${{ env.CI_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BRANCH_NAME }}
+        run: ./gradlew bootBuildImage --publishImage --imageName ${{ env.CI_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
+
+  deploy-staging:
+    runs-on: ubuntu-24.04
+    environment: staging
+    # How to run Ansible (https://stackoverflow.com/a/74169157/6310030)
+    steps:
+      - name: Checkout Sources
+        uses: actions/checkout@v4
+      - name: Setup SSH
+        run: |
+          eval $(ssh-agent -s)
+          
+          mkdir ~/.ssh
+          chmod 700 ~/.ssh
+          
+          touch ~/.ssh/id_rsa
+          chmod 400 ~/.ssh/id_rsa
+          echo -e "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
+          
+          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.$SSH_KNOWN_HOSTS}} >> ~/.ssh/known_hosts
+      - name: Run ansible script
+        run: |
+          cd infra/ansible
+          ansible-playbook -i production site.yml
